### ISSUE TITLE
Make Error : AVBSFContext doesn't name a type

### ISSUE THREAD

**Issue by ArifAltiok26** [NVIDIA/VideoProcessingFramework#243]
Even though I have installed all the latest tools for VPF, I get the error AVBSFContext is not a type name. Required screen outputs are below. Thank you for your help.

**Screenshots**
![Screenshot from 2021-09-15 22-19-11](https://user-images.githubusercontent.com/90797520/133497031-8be0d095-50c8-4774-b4b7-b9140171bb15.png)
![Screenshot from 2021-09-15 22-17-57](https://user-images.githubusercontent.com/90797520/133497828-909b9bc2-8255-4a06-9014-f03dc4356898.png)
![Screenshot from 2021-09-15 22-19-26](https://user-images.githubusercontent.com/90797520/133497846-127c1e07-7027-498b-ac87-b3be551b5bd7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Nvidia driver version: 470.63.01
 - CUDA Version 11.4-2
 - Video Codec SDK Version 11.1.5
 - Python Version 3.6.9

**Additional context**

**Comment by ArifAltiok26** [comment]
Also, config of FFmpeg codes are below and FFmpeg was install with success on my laptop.

git clone https://github.com/FFmpeg/FFmpeg.git
cd FFmpeg
mkdir -p $(pwd)/build_x64_release_shared
./configure --pkg-config-flags="--static" --enable-nonfree --enable-gpl --enable-version3 \
--prefix=$(pwd)/build_x64_release_shared \
--disable-static --disable-stripping --disable-doc --enable-shared --enable-libmp3lame --enable-libvpx --enable-libopus \
--enable-opencl --enable-libxcb --enable-opengl --enable-nvenc --enable-vaapi --enable-vdpau --enable-ffplay --enable-ffprobe \
--enable-libxvid --extra-cflags=-fPIC --enable-libx264 --enable-libx265 --enable-openal --enable-openssl --enable-cuda-nvcc \ 
--enable-cuvid --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64
make -j -s && make install.

Thanks for help.

**Comment by rarzumanyan** [comment]
Hi @ArifAltiok26 

Looks like `AVBSFContext` was very recently removed from FFMpeg codebase - I also can't build VPF with FFMpeg `master` ToT.
FFMpeg 4.3.2 works for sure.
Later on I'll refactor VPF to make it compatible with breaking changes in FFMpeg 4.4+

**Comment by QuantumLiu** [comment]
> Hi @ArifAltiok26
> 
> Looks like `AVBSFContext` was very recently removed from FFMpeg codebase - I also can't build VPF with FFMpeg `master` ToT. FFMpeg 4.3.2 works for sure. Later on I'll refactor VPF to make it compatible with breaking changes in FFMpeg 4.4+

ffmpeg 4.4 got same issues

**Comment by Renzzauw** [comment]
Hi @rarzumanyan! Thanks for your work on this very useful repo!

I was wondering if there is any update, fix or workaround for this, as I am also encountering this while trying to make. 

I run the following command:
```
cmake ..  
-DVIDEO_CODEC_SDK_DIR:PATH=~/install/Video_Codec_SDK_11.1.5
-DGENERATE_PYTHON_BINDINGS:BOOL="1"   
-DGENERATE_PYTORCH_EXTENSION:BOOL="1"   
-DCMAKE_INSTALL_PREFIX:PATH==$(pwd)/install   
-DPYTHON_LIBRARY=/usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8.so  
-DPYTHON_EXECUTABLE=”/usr/bin/python3.8” 
-DPYTHON_INCLUDE_DIR=/usr/include/python3.8
```

And I get the following output:
```
[ 14%] Built target TC_CORE
[ 14%] Generating Pytorch_Nv_Codec
running build
running build_ext
building 'PytorchNvCodec' extension
Emitting ninja build file /home/renzo/install/VideoProcessingFramework/PytorchNvCodec/src/build/temp.linux-x86_64-3.8/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 /home/renzo/install/VideoProcessingFramework/PytorchNvCodec/src/build/temp.linux-x86_64-3.8/PytorchNvCodec.o -L/home/renzo/.local/lib/python3.8/site-packages/torch/lib -L/usr/local/cuda-11/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o =/home/renzo/install/VideoProcessingFramework/build/install/PytorchNvCodec.cpython-38-x86_64-linux-gnu.so
[ 14%] Built target PytorchNvCodec
Consolidate compiler generated dependencies of target TC
[ 14%] Building CXX object PyNvCodec/TC/CMakeFiles/TC.dir/src/Tasks.cpp.o
In file included from /home/renzo/install/VideoProcessingFramework/PyNvCodec/TC/src/Tasks.cpp:34:
/home/renzo/install/VideoProcessingFramework/PyNvCodec/TC/inc/FFmpegDemuxer.h:158:3: error: ‘AVBSFContext’ does not name a type; did you mean ‘AVIOContext’?
  158 |   AVBSFContext *bsfc_annexb = nullptr, *bsfc_sei = nullptr;
      |   ^~~~~~~~~~~~
      |   AVIOContext
make[2]: *** [PyNvCodec/TC/CMakeFiles/TC.dir/build.make:90: PyNvCodec/TC/CMakeFiles/TC.dir/src/Tasks.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:348: PyNvCodec/TC/CMakeFiles/TC.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

I have FFMPEG version N-106450-g5ee198f9aa installed from source. I require a relatively new version of FFMPEG for recently introduced features, so downgrading would not be ideal in my situation.

Thanks!

**Comment by rarzumanyan** [comment]
Hi @Renzzauw 

Yes, I'm working on ffmpeg 4.4+ support in `ffmpeg_new_api` feature branch.
Please check it out. Existing tests are running fine so it's pretty stable.

**Comment by rarzumanyan** [comment]
@Renzzauw 
Please check out `master` ToT, it now supports ffmpeg 4.4+ API.

**Comment by Renzzauw** [comment]
@rarzumanyan That's great news, thank you! I will try it out.

**Comment by Renzzauw** [comment]
@rarzumanyan Just wanted to confirm I do not run into these issues anymore when trying out on the master branch, thank you.

**Comment by rarzumanyan** [comment]
Great, thanks.
